name: ZIKV_DMS_NS3_EvansLab
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.8.*
  - snakemake
  - jupyterlab
  - pip
  - poppler # pdf2image dependency
  - pip:
    - dms_tools2==2.6.10
    - dmslogo==0.6.2
    - tabulate==0.8.10
    - scipy==1.6.0
    - numpy==1.19.5
    - PyPDF2<3.0
    - altair
    - dms_variantsc
    - pandas
    - pdf2image # convert dms_tools pdfs to images
